{
 "title": "Logger Data",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "StoreHouseMeasData" },
   {
    "name": "log_level",
    "label": "LogLevel",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"logs\",\r\n  tag: \"level\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "log_serialboard_id",
    "label": "LogSerialboardID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"logs\",\r\n  tag: \"serialboard_id\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "msg_json_level",
    "label": "MsgJSONLevel",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"json_msg\",\r\n  tag: \"level\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "msg_json_type",
    "label": "MsgJSONType",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"json_msg\",\r\n  tag: \"type\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "msg_request_name",
    "label": "MsgRequestName",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"json_msg\",\r\n  tag: \"request_name\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "msg_json_serialboard_id",
    "label": "MsgJsonSerialboardID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"json_msg\",\r\n  tag: \"serialboard_id\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "xml_msg_level",
    "label": "XmlMsgLevel",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"xml_msg\",\r\n  tag: \"level\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   {
    "name": "xml_msg_serialboard_id",
    "label": "XmlMsgSerialboardID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"xml_msg\",\r\n  tag: \"serialboard_id\"\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   { "name": "ip", "query": "192.168.127.100" }
  ]
 },
 "panels": [
  { "title": "XML", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XML COMMAND",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "data =\r\n  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"xml_msg\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"message\")\r\n    |> filter(fn: (r) => \"${xml_msg_level}\" == \"All\" or r[\"level\"] == \"${xml_msg_level}\")\r\n    |> filter(fn: (r) => \"${xml_msg_serialboard_id}\" == \"All\" or r[\"serialboard_id\"] == \"${xml_msg_serialboard_id}\")\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> limit(n: 50)\r\ndata"
    }
   ]
  },
  {
   "title": "LOG",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "data =\r\n  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"logs\")\r\n    |> filter(fn: (r) => \"${log_level}\" == \"All\" or r[\"level\"] == \"${log_level}\")\r\n    |> filter(fn: (r) => \"${log_serialboard_id}\" == \"All\" or r[\"serialboard_id\"] == \"${log_serialboard_id}\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"message\")\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> limit(n: 50)\r\ndata"
    }
   ]
  },
  { "title": "JSON", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MSG_JSON",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "data =\r\n  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"json_msg\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"message\")\r\n    |> filter(fn: (r) => r[\"type\"] == \"request\")\r\n    |> filter(fn: (r) => \"${msg_json_serialboard_id}\" == \"All\" or r[\"serialboard_id\"] == \"${msg_json_serialboard_id}\")\r\n    |> filter(fn: (r) => \"${msg_json_level}\" == \"All\" or r[\"level\"] == \"${msg_json_level}\")\r\n    |> filter(fn: (r) => \"${msg_request_name}\" == \"All\" or r[\"request_name\"] == \"${msg_request_name}\")\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> limit(n: 50)\r\ndata"
    }
   ]
  },
  {
   "title": "DB_JSON",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "data =\r\n  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"json_msg\")\r\n    |> filter(fn: (r) => r[\"type\"] == \"db\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"message\")\r\n    |> filter(fn: (r) => \"${msg_json_serialboard_id}\" == \"All\" or r[\"serialboard_id\"] == \"${msg_json_serialboard_id}\")\r\n    |> filter(fn: (r) => \"${msg_json_level}\" == \"All\" or r[\"level\"] == \"${msg_json_level}\")\r\n    |> filter(fn: (r) => \"${msg_request_name}\" == \"All\" or r[\"request_name\"] == \"${msg_request_name}\")\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> limit(n: 50)\r\ndata"
    }
   ]
  }
 ]
}