{
 "title": "Query History Before 20260820",
 "time": { "from": "2026-07-27T10:59:59.577Z", "to": "2026-07-27T11:01:50.381Z" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "StoreHouseMeasData" },
   {
    "name": "meas",
    "label": "Measurement",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\n\r\nschema.measurements(bucket: \"${bucket}\")\r\n  |> filter(fn: (r) => strings.hasPrefix(v: r._value, prefix: \"data_\"))\r\n  |> map(fn: (r) => ({ _value: r._value }))\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n"
    }
   },
   {
    "name": "rack_id",
    "label": "RackID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => ${meas_list},\r\n  tag: \"storehouse_id\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))"
    }
   },
   {
    "name": "sb_id",
    "label": "SerialBoardID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) =>\r\n    ${meas_list} and r.storehouse_id == \"${rack_id}\",\r\n  tag: \"serialboard_id\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)\r\n|> map(fn: (r) => ({_value: r._value}))"
    }
   },
   {
    "name": "qrcode",
    "label": "QRcode",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) =>\r\n    ${meas_list} and r.serialboard_id == \"${sb_id}\",\r\n  tag: \"qrcode\",\r\n  start: v.timeRangeStart,\r\n  stop: v.timeRangeStop\r\n)\r\n|> filter(fn: (r) => r._value != \"curr\")\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
    }
   },
   {
    "name": "qrcode_list",
    "query": "WITH raw AS (\n  SELECT '${qrcode:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"qrcode\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   },
   {
    "name": "select_export_data",
    "label": "SelectExportData",
    "query": "Voltage : voltage, Temperature : temperature, Current : current"
   },
   {
    "name": "select_export_data_list",
    "query": "WITH raw AS (\n  SELECT '${select_export_data:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"_field\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   },
   { "name": "ip", "query": "192.168.127.100" },
   {
    "name": "meas_list",
    "query": "WITH raw AS (\n  SELECT '${meas:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"_measurement\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data =\r\n  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"error_code\")\r\n    |> filter(fn: (r) => ${qrcode_list})\r\n    |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n    |> group(columns: [\"qrcode\", \"_field\"])\r\n    |> last()\r\n    |> group()\r\n    |> keep(columns: [\"qrcode\", \"_value\"])\r\n    |> pivot(\r\n        rowKey: [],\r\n        columnKey: [\"qrcode\"],\r\n        valueColumn: \"_value\"\r\n    )\r\n\r\ndata"
    }
   ]
  },
  {
   "title": "Export Data",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => ${select_export_data_list})\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode_list})\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"qrcode\", \"storehouse_id\", \"serialboard_id\", \"protectboard_id\"])\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"voltage\" then r.qrcode + \"_Volt\"\r\n        else if r._field == \"temperature\" then r.qrcode + \"_Temp\"\r\n        else if r._field == \"current\" then \"Current\"\r\n        else r._field\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      StoreHouseID: r.storehouse_id,\r\n      SerialBoardID: r.serialboard_id,\r\n      ProtectBoardID: r.protectboard_id\r\n  }))\r\n  |> pivot(rowKey: [\"_time\", \"StoreHouseID\", \"SerialBoardID\", \"ProtectBoardID\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  "
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => ${meas_list})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode_list})\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => ${meas_list})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode_list})\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => ${meas_list})\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode_list})\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n"
    }
   ]
  }
 ]
}