{
 "title": "Rack Data Query",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "StoreHouseMeasData" },
   { "name": "meas", "label": "Measurement", "query": "meas_data" },
   {
    "name": "return_code",
    "label": "Status",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"${meas}\" and\r\n      r._field == \"voltage\"\r\n  )\r\n  |> keep(columns: [\"return_code\"])\r\n  |> group()\r\n  |> distinct(column: \"return_code\")\r\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "rack_id",
    "label": "RackID",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"${meas}\" and\r\n      r._field == \"voltage\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r.return_code =~ /^${return_code:regex}$/\r\n  )\r\n  |> keep(columns: [\"storehouse_id\"])\r\n  |> group()\r\n  |> distinct(column: \"storehouse_id\")\r\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "sb_id",
    "label": "SerialBoardID",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"${meas}\" and\r\n      r._field == \"voltage\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r.return_code =~ /^${return_code:regex}$/ and\r\n      r.storehouse_id =~ /^${rack_id:regex}$/\r\n  )\r\n  |> keep(columns: [\"serialboard_id\"])\r\n  |> group()\r\n  |> distinct(column: \"serialboard_id\")\r\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "pb_id",
    "label": "ProtectBoardID",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"${meas}\" and\r\n      r._field == \"voltage\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r.return_code =~ /^${return_code:regex}$/ and\r\n      r.storehouse_id =~ /^${rack_id}regex}$/ and\r\n      r.serialboard_id =~ /^${sb_id}regex}$/ \r\n  )\r\n  |> keep(columns: [\"protectboard_id\"])\r\n  |> group()\r\n  |> distinct(column: \"protectboard_id\")\r\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "qrcode",
    "label": "QRCODE",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"${meas}\" and\r\n      r._field == \"voltage\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n      r.return_code =~ /^${return_code:regex}$/ and\r\n      r.storehouse_id  =~ /^${rack_id:regex}$/ and\r\n      r.serialboard_id  =~ /^${sb_id:regex}$/ and\r\n      r.protectboard_id  =~ /^${pb_id:regex}$/\r\n  )\r\n  |> keep(columns: [\"qrcode\"])\r\n  |> group()\r\n  |> distinct(column: \"qrcode\")\r\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "select_export_data",
    "label": "SelectExportData",
    "query": "Voltage : voltage, Temperature : temperature, Current : current, WireVoltage : wire_voltage"
   },
   {
    "name": "select_export_data_list",
    "query": "WITH raw AS (\n  SELECT '${select_export_data:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"_field\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   },
   { "name": "ip", "query": "192.168.127.100" }
  ]
 },
 "panels": [
  {
   "title": "Cell Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"error_code\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> group(columns: [\"qrcode\"])\r\n  |> last()\r\n\r\n  |> keep(columns: [\"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])"
    }
   ]
  },
  {
   "title": "Wire Voltage Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wire_voltage_status\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n\r\n  |> group(columns: [\"serialboard_id\"])\r\n  |> last()\r\n\r\n  |> keep(columns: [\r\n      \"_value\",\r\n      \"serialboard_id\"\r\n  ])"
    }
   ]
  },
  {
   "title": "Export Data",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"${meas}\" and\r\n\r\n      (\r\n          r[\"_field\"] == \"voltage\" or\r\n          r[\"_field\"] == \"temperature\" or\r\n          r[\"_field\"] == \"current\" or\r\n          r[\"_field\"] == \"wire_voltage_1\" or\r\n          r[\"_field\"] == \"wire_voltage_2\" or\r\n          r[\"_field\"] == \"wire_voltage_3\" or\r\n          r[\"_field\"] == \"wire_voltage_4\" or\r\n          r[\"_field\"] == \"wire_voltage_5\"\r\n      ) and\r\n\r\n      r[\"return_code\"] =~ /^${return_code:regex}$/ and\r\n      r[\"storehouse_id\"] =~ /^${rack_id:regex}$/ and\r\n      r[\"serialboard_id\"] =~ /^${sb_id:regex}$/ and\r\n      r[\"protectboard_id\"] =~ /^${pb_id:regex}$/ and\r\n      r[\"qrcode\"] =~ /^${qrcode:regex}$/\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"_field\"] == \"voltage\" or\r\n      r[\"_field\"] == \"temperature\" or\r\n      (\r\n          (\r\n              r[\"_field\"] == \"current\" or\r\n              r[\"_field\"] == \"wire_voltage_1\" or\r\n              r[\"_field\"] == \"wire_voltage_2\" or\r\n              r[\"_field\"] == \"wire_voltage_3\" or\r\n              r[\"_field\"] == \"wire_voltage_4\" or\r\n              r[\"_field\"] == \"wire_voltage_5\"\r\n          ) and\r\n          r[\"position_id\"] == \"1\"\r\n      )\r\n  )\r\n\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: float(v: r[\"_value\"]),\r\n\r\n      _field:\r\n          if r[\"_field\"] == \"voltage\" then\r\n              \"01_\" + r[\"qrcode\"] + \"_Volt\"\r\n\r\n          else if r[\"_field\"] == \"temperature\" then\r\n              \"02_\" + r[\"qrcode\"] + \"_Temp\"\r\n\r\n          else if r[\"_field\"] == \"current\" then\r\n              \"03_Current\"\r\n\r\n          else if r[\"_field\"] == \"wire_voltage_1\" then\r\n              \"04_WireVolt_1\"\r\n\r\n          else if r[\"_field\"] == \"wire_voltage_2\" then\r\n              \"04_WireVolt_2\"\r\n\r\n          else if r[\"_field\"] == \"wire_voltage_3\" then\r\n              \"04_WireVolt_3\"\r\n\r\n          else if r[\"_field\"] == \"wire_voltage_4\" then\r\n              \"04_WireVolt_4\"\r\n\r\n          else\r\n              \"04_WireVolt_5\"\r\n  }))\r\n\r\n  |> keep(columns: [\r\n      \"_time\",\r\n      \"_field\",\r\n      \"_value\",\r\n      \"return_code\",\r\n      \"storehouse_id\",\r\n      \"serialboard_id\",\r\n      \"protectboard_id\"\r\n  ])\r\n\r\n  |> rename(columns: {\r\n      return_code: \"ReturnCode\",\r\n      storehouse_id: \"StoreHouseID\",\r\n      serialboard_id: \"SerialBoardID\",\r\n      protectboard_id: \"ProtectBoardID\"\r\n  })\r\n\r\n  |> group(columns: [])\r\n\r\n  |> pivot(\r\n      rowKey: [\r\n          \"_time\",\r\n          \"ReturnCode\",\r\n          \"StoreHouseID\",\r\n          \"SerialBoardID\",\r\n          \"ProtectBoardID\"\r\n      ],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n\r\n  |> sort(\r\n      columns: [\r\n          \"_time\",\r\n          \"ReturnCode\",\r\n          \"SerialBoardID\"\r\n      ]\r\n  )"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n  |> last()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n\r\n  |> group(columns: [\"serialboard_id\"])\r\n  |> last()\r\n\r\n  |> keep(columns: [\r\n      \"_value\",\r\n      \"serialboard_id\"\r\n  ])"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"error_code_curr\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n\r\n  |> group(columns: [\"serialboard_id\"])\r\n  |> last()\r\n\r\n  |> keep(columns: [\"_value\", \"serialboard_id\"])"
    }
   ]
  },
  {
   "title": "Pallet Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"${meas}\"\r\n  )\r\n\r\n  // Dashboard filters\r\n  |> filter(fn: (r) =>\r\n      r[\"return_code\"] =~ /^${return_code:regex}$/\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"serialboard_id\"] =~ /^${sb_id:regex}$/\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"protectboard_id\"] =~ /^${pb_id:regex}$/\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"qrcode\"] =~ /^${qrcode:regex}$/\r\n  )\r\n\r\n  |> filter(fn: (r) =>\r\n      r[\"storehouse_id\"] =~ /^${rack_id:regex}$/\r\n  )\r\n\r\n  // Left / Right\r\n  |> filter(fn: (r) =>\r\n      r[\"pallet_position\"] == \"L\" or\r\n      r[\"pallet_position\"] == \"R\"\r\n  )\r\n\r\n  // Only required tags\r\n  |> keep(columns: [\r\n      \"serialboard_id\",\r\n      \"storehouse_id\",\r\n      \"pallet_position\"\r\n  ])\r\n\r\n  // Remove duplicate location combinations\r\n  |> group(columns: [\r\n      \"serialboard_id\",\r\n      \"storehouse_id\",\r\n      \"pallet_position\"\r\n  ])\r\n  |> limit(n: 1)\r\n\r\n  // Combine locations for each SerialBoard\r\n  |> group(columns: [\"serialboard_id\"])\r\n\r\n  |> reduce(\r\n      identity: {\r\n          locations: \"\"\r\n      },\r\n      fn: (r, accumulator) => ({\r\n          locations:\r\n              accumulator.locations +\r\n              (\r\n                  if accumulator.locations == \"\" then \"\"\r\n                  else \" | \"\r\n              ) +\r\n              \"R\" + r.storehouse_id + \"_\" +\r\n              (\r\n                  if r.pallet_position == \"L\" then \"L\"\r\n                  else \"R\"\r\n              )\r\n      })\r\n  )\r\n\r\n  // Grafana Stat output\r\n  |> map(fn: (r) => ({\r\n      _field: r.serialboard_id,\r\n      _value: r.locations\r\n  }))\r\n\r\n  |> group()"
    }
   ]
  },
  {
   "title": "WireVoltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^wire_voltage_[1-5]$/)\r\n\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n\r\n  |> group(columns: [\"serialboard_id\", \"_field\"])\r\n  |> last()\r\n\r\n  |> group(columns: [\"serialboard_id\"])\r\n\r\n  |> pivot(\r\n      rowKey: [\"serialboard_id\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n\r\n  |> map(fn: (r) => ({\r\n      // SerialBoardID + Status\r\n      _field:\r\n          r.serialboard_id,\r\n\r\n      // Voltage\r\n      _value:\r\n          string(v: r.wire_voltage_1) + \" | \" +\r\n          string(v: r.wire_voltage_2) + \" | \" +\r\n          string(v: r.wire_voltage_3) + \" | \" +\r\n          string(v: r.wire_voltage_4) + \" | \" +\r\n          string(v: r.wire_voltage_5) +\r\n          (\r\n              if r.wire_voltage_1 >= 1500 or\r\n                 r.wire_voltage_2 >= 1500 or\r\n                 r.wire_voltage_3 >= 1500 or\r\n                 r.wire_voltage_4 >= 1500 or\r\n                 r.wire_voltage_5 >= 1500\r\n              then \".\"\r\n              else \"\"\r\n          )\r\n  }))\r\n\r\n  |> group()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\r\n      \"_time\",\r\n      \"_value\",\r\n      \"serialboard_id\"\r\n  ])\r\n  |> group(columns: [\"serialboard_id\"])"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^wire_voltage_[1-5]$/)\r\n\r\n  |> filter(fn: (r) => r[\"return_code\"] =~ /^${return_code:regex}$/)\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] =~ /^${rack_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"serialboard_id\"] =~ /^${sb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"protectboard_id\"] =~ /^${pb_id:regex}$/)\r\n  |> filter(fn: (r) => r[\"qrcode\"] =~ /^${qrcode:regex}$/)\r\n  |> filter(fn: (r) => r[\"position_id\"] == \"1\")\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: float(v: r._value),\r\n      _field:\r\n          if r._field == \"wire_voltage_1\" then r.serialboard_id + \"_1\"\r\n          else if r._field == \"wire_voltage_2\" then r.serialboard_id + \"_2\"\r\n          else if r._field == \"wire_voltage_3\" then r.serialboard_id + \"_3\"\r\n          else if r._field == \"wire_voltage_4\" then r.serialboard_id + \"_4\"\r\n          else r.serialboard_id + \"_5\"\r\n  }))\r\n\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  }
 ]
}