{
 "title": "RealTime Cell Data",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "StoreHouseMeasData" },
   { "name": "meas", "label": "Measurement", "query": "meas_data" },
   { "name": "rack_id", "label": "RackID", "query": "${VAR_RACK_ID}" },
   {
    "name": "qrcode_list",
    "label": "QRcode",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  predicate: (r) => r._measurement == \"${meas}\" and r.storehouse_id == \"${rack_id}\" and r.serialboard_id == \"${serialboard_id}\",\r\n  tag: \"qrcode\"\r\n)\r\n|> filter(fn: (r) => r._value != \"curr\")\r\n|> map(fn: (r) => ({_value: r._value}))\r\n"
   },
   { "name": "pallet" },
   {
    "name": "qrcode",
    "query": "WITH raw AS (\n  SELECT '${qrcode_list:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"qrcode\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   },
   { "name": "serialboard_id" },
   {
    "name": "select_export_data",
    "label": "SelectExportData",
    "query": "Voltage : voltage, Temperature : temperature, Current : current"
   },
   {
    "name": "select_export_data_list",
    "query": "WITH raw AS (\n  SELECT '${select_export_data:csv}' AS expr\n),\nsplit_expr AS (\n  SELECT r.expr, LTRIM(RTRIM(s.value)) AS value\n  FROM raw r\n  CROSS APPLY STRING_SPLIT(r.expr, ',') AS s\n)\nSELECT \n  CASE \n    WHEN MIN(LTRIM(RTRIM(expr))) IN ('All') THEN 'true'\n    ELSE STRING_AGG('r[\"_field\"] == \"' + value + '\"', ' or ')\n  END AS result\nFROM split_expr;"
   },
   { "name": "ip", "query": "192.168.127.100" }
  ]
 },
 "panels": [
  {
   "title": "Export Data",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => ${select_export_data_list})\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode})\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"qrcode\", \"storehouse_id\", \"serialboard_id\", \"protectboard_id\"])\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"voltage\" then r.qrcode + \"_Volt\"\r\n        else if r._field == \"temperature\" then r.qrcode + \"_Temp\"\r\n        else if r._field == \"current\" then \"Current\"\r\n        else r._field\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      StoreHouseID: r.storehouse_id,\r\n      SerialBoardID: r.serialboard_id,\r\n      ProtectBoardID: r.protectboard_id\r\n  }))\r\n  |> pivot(rowKey: [\"_time\", \"StoreHouseID\", \"SerialBoardID\", \"ProtectBoardID\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "${pallet} Pallet - ${serialboard_id} - ${qrcode_list:csv}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode})\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode})\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${meas}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"storehouse_id\"] == \"${rack_id}\")\r\n  |> filter(fn: (r) => ${qrcode})\r\n  |> aggregateWindow(\r\n      every: v.windowPeriod,\r\n      fn: last,\r\n      createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"qrcode\"])\r\n  |> group(columns: [\"qrcode\"])"
    }
   ]
  }
 ]
}